from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.shared import Pt, Inches
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


def _set_cell_shading(cell, fill):
    """Set background color for a table cell."""
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), fill)
    cell._tc.get_or_add_tcPr().append(shading)


def generate_inspection_docx(inspection, output_path):
    """
    Generate an editable DOCX compliance inspection report.

    Parameters:
        inspection (dict): Inspection data.
        output_path (str): Path where the DOCX will be saved.
    """

    document = Document()

    # Page margins
    section = document.sections[0]
    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.75)
    section.right_margin = Inches(0.75)

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run("Packaged Commodity Compliance Report")
    run.bold = True
    run.font.size = Pt(20)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = subtitle.add_run("Legal Metrology Inspection")
    run.italic = True
    run.font.size = Pt(11)

    document.add_paragraph()

    # --------------------------------------------------
    # Inspection data
    # --------------------------------------------------

    product_name = inspection.get("productName", "N/A")
    inspection_id = inspection.get("id", "N/A")
    date = inspection.get("date", "N/A")
    status = inspection.get("status", "N/A")
    score = inspection.get("complianceScore", 0)

    details = [
        ("Product Name", product_name),
        ("Inspection ID", inspection_id),
        ("Inspection Date", date),
        ("Compliance Status", status),
        ("Compliance Score", f"{score}%"),
    ]

    table = document.add_table(rows=len(details), cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"

    for row, (label, value) in zip(table.rows, details):
        row.cells[0].text = str(label)
        row.cells[1].text = str(value)

        _set_cell_shading(row.cells[0], "E2E8F0")

        row.cells[0].vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        row.cells[1].vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER

        for run in row.cells[0].paragraphs[0].runs:
            run.bold = True

    document.add_paragraph()

    # --------------------------------------------------
    # Violations
    # --------------------------------------------------

    heading = document.add_paragraph()
    run = heading.add_run("Violations Detected")
    run.bold = True
    run.font.size = Pt(14)

    violations = inspection.get("violations", [])

    if violations:
        violation_table = document.add_table(
            rows=1,
            cols=2
        )
        violation_table.style = "Table Grid"
        violation_table.alignment = WD_TABLE_ALIGNMENT.CENTER

        header = violation_table.rows[0].cells
        header[0].text = "#"
        header[1].text = "Violation"

        _set_cell_shading(header[0], "FEE2E2")
        _set_cell_shading(header[1], "FEE2E2")

        for cell in header:
            for run in cell.paragraphs[0].runs:
                run.bold = True

        for index, violation in enumerate(violations, start=1):
            cells = violation_table.add_row().cells
            cells[0].text = str(index)
            cells[1].text = str(violation)

    else:
        paragraph = document.add_paragraph()
        paragraph.add_run(
            "No violations detected. The product is compliant "
            "with the evaluated requirements."
        )

    # --------------------------------------------------
    # Evidence section
    # --------------------------------------------------

    document.add_paragraph()

    heading = document.add_paragraph()
    run = heading.add_run("Supporting Evidence")
    run.bold = True
    run.font.size = Pt(14)

    evidence = inspection.get("evidence", [])

    if evidence:
        for item in evidence:
            document.add_paragraph(str(item), style="List Bullet")
    else:
        document.add_paragraph(
            "No supporting evidence was attached to this inspection."
        )

    # --------------------------------------------------
    # Footer note
    # --------------------------------------------------

    document.add_paragraph()

    note = document.add_paragraph()
    run = note.add_run(
        "This report was generated by the Packaged Commodity Inspector system."
    )
    run.font.size = Pt(9)
    run.italic = True

    # --------------------------------------------------
    # Save
    # --------------------------------------------------

    document.save(output_path)